# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: adespond <adespond@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2015/09/15 20:02:56 by adespond          #+#    #+#              #
#    Updated: 2015/09/16 04:48:54 by adespond         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

SRC = ./main6.c

FLAGS = -Wall -Wextra -Werror

all:
	gcc $(FLAGS) -o do-op $(SRC)

clean:
	/bin/rm -f $(OBJECT)
